Document: dmidecode
Title: Debian dmidecode Manual
Author: <insert document author here>
Abstract: This manual describes what dmidecode is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/dmidecode/dmidecode.sgml.gz

Format: postscript
Files: /usr/share/doc/dmidecode/dmidecode.ps.gz

Format: text
Files: /usr/share/doc/dmidecode/dmidecode.text.gz

Format: HTML
Index: /usr/share/doc/dmidecode/html/index.html
Files: /usr/share/doc/dmidecode/html/*.html

  
